[project]
	type = "library"
	name = "stream"
	description = "Very light implementation for streams"
	version = "1.0.0" 

	[project.cmake]
		include = "cmake/stream.cmake"

[packaging]
	include = [
		"cmake",
		"src"
	]

