name = "stream"
description = "Very light stream implementation without memory allocation"
version = "1.0.0" 

[cmake]
	include = "cmake/stream.cmake"

[packaging]
	include = [
		"cmake",
		"src"
	]

